In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 66.1 MB/s eta 0:00:00


In [10]:
import gensim
import os
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
!ls

archive.zip  sample_data


In [7]:
!unzip archive.zip

Archive:  archive.zip
  inflating: 001ssb.txt              
  inflating: 002ssb.txt              
  inflating: 003ssb.txt              
  inflating: 004ssb.txt              
  inflating: 005ssb.txt              


In [8]:
!ls

001ssb.txt  003ssb.txt	005ssb.txt   sample_data
002ssb.txt  004ssb.txt	archive.zip


In [12]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import os

story = []

for filename in os.listdir('.'):
    if filename.endswith('.txt'):
        with open(filename, 'r', errors='ignore') as f:
            corpus = f.read()
            raw_sent = sent_tokenize(corpus)
            for sent in raw_sent:
                story.append(simple_preprocess(sent))

In [13]:
story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [16]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [17]:
model.build_vocab(story)

In [18]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(6574942, 8625265)

In [19]:
model.wv.most_similar('daenerys')

[('stormborn', 0.8140579462051392),
 ('targaryen', 0.8026188015937805),
 ('unburnt', 0.7605454921722412),
 ('princess', 0.725303590297699),
 ('myrcella', 0.6958752870559692),
 ('rhaegar', 0.6944442987442017),
 ('elia', 0.6918365359306335),
 ('queen', 0.6826894283294678),
 ('aegon', 0.6755551099777222),
 ('margaery', 0.6679234504699707)]

In [21]:
model.wv.doesnt_match(['jon','robb','arya','sansa','bran'])

'jon'

In [22]:
model.wv.doesnt_match(['cersei', 'jaime', 'bronn', 'tyrion'])

'bronn'

In [23]:
model.wv['king']

array([ 2.6523492 ,  1.4685844 , -0.21375991, -1.8634653 , -2.182148  ,
        2.9120152 ,  0.7877699 , -0.5095793 , -0.22689715,  1.1995494 ,
       -1.4046268 ,  0.7279958 , -2.5981636 ,  1.1173972 , -0.33109623,
       -2.9126225 ,  1.1625853 , -1.9247081 , -5.166132  , -1.5504317 ,
        3.2427015 ,  2.6315858 , -1.2941272 , -2.1473029 ,  0.21746089,
       -0.41674146, -1.5318104 , -0.2412671 , -0.71420133,  1.2586737 ,
       -0.29868782,  2.3659327 , -1.4666407 , -2.371991  ,  1.889067  ,
        1.253583  ,  1.2162025 , -1.6320488 , -1.4995524 ,  0.7443029 ,
       -1.5773618 ,  0.3141008 ,  1.568352  ,  0.7055121 ,  0.7825094 ,
       -2.1921132 ,  0.08534724, -0.3905446 ,  3.1089392 ,  0.36588672,
       -0.50324   , -0.009014  ,  0.2231656 , -0.7458504 , -0.8415144 ,
        0.02391774, -1.2247827 , -0.33566102, -0.7884984 ,  0.31772122,
        2.3591018 ,  1.6149782 ,  0.97282434,  2.6296167 ,  0.23035981,
       -0.6813661 , -0.090827  , -0.12422887, -0.56877756, -0.97

In [24]:
model.wv.similarity('arya','sansa')

np.float32(0.8427897)

In [25]:
model.wv.similarity('cersei','sansa')

np.float32(0.77181154)

In [26]:
model.wv.similarity('tywin','sansa')

np.float32(0.22859651)

In [27]:
model.wv.get_normed_vectors()

array([[ 0.12738924, -0.03554301,  0.13968767, ..., -0.1296696 ,
        -0.02460645,  0.09979108],
       [ 0.04119471, -0.00561496,  0.03810237, ...,  0.06086648,
        -0.06153721,  0.00072616],
       [ 0.04977372, -0.05371597, -0.07393951, ..., -0.14625546,
         0.12706938, -0.15243393],
       ...,
       [-0.1085177 , -0.02889582, -0.01852651, ...,  0.02735846,
         0.17367907,  0.01204206],
       [ 0.07921193,  0.06720316, -0.03907635, ..., -0.10530724,
         0.00756456,  0.02116046],
       [ 0.11539843, -0.05319038,  0.07599044, ...,  0.025171  ,
         0.01417578, -0.12032368]], dtype=float32)

In [28]:
y = model.wv.index_to_key
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'them',
 'lord',
 'no',
 'from',
 'were',
 'would',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'are',
 'we',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'king',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'old',
 'hand',
 'even',
 'too',
 'before',
 'never',
 'tyrion',
 'off',
 'an',
 'know',
 'see',
 'into',
 'made',
 'father',
 'now',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'then',
 'how',
 'long',
 'has',
 'might',
 'us',
 'come',
 'where',
 'here',
 'can',
 'through',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'once',
 'good',
 'two',
 'over',
 'little',
 'about',
 'brother'

In [29]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X = pca.fit_transform(model.wv.get_normed_vectors())
X

array([[ 0.20605196, -0.5915388 ,  0.03121118],
       [ 0.20527558, -0.31938273, -0.07847227],
       [-0.2724524 , -0.59241337, -0.23395187],
       ...,
       [-0.09704335, -0.11203581, -0.2287583 ],
       [ 0.06635414, -0.0635778 ,  0.13618897],
       [-0.29103893, -0.30064264, -0.10767913]], dtype=float32)

In [30]:
X.shape

(17869, 3)

In [31]:
import plotly.express as px
fig = px.scatter_3d(X[200:300],x=0,y=1,z=2, color=y[200:300])
fig.show()